import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const home: React.CSSProperties = {
    display: 'grid',
    placeItems: 'center',
    // height: '60px',
    backgroundColor: '#1a1a1a',
    color: 'white',
    fontSize: '24px',
    fontWeight: 'bold',
  };
  return (
    <html lang="en">
      <body className={inter.className} style={home}>
      <Navbar></Navbar>
        {children}
      <Footer></Footer>
      </body>
    </html>
  );
}
